apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: helloworl1
    repoURL: 'https://github.com/abhishek3100/argocd.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true